### ISSUE TITLE
Photo Home

### ISSUE THREAD

**Issue by Breezee15** [hzuapps/uml-modeling-2020#199]
这是一个类似社交的软件，
1. 日常推送一些关注的用户（或是高粉丝量用户）的精选照片。
2. 可以为精美的图片点赞
3. 可以搜索图片

**Comment by zengsn** [comment]
还改吗？

**Comment by Breezee15** [comment]
老师，我当时没有在这里修改，而是发布了新的选题，题号是 #705 ，已经被你选题通过了，辛苦了老师。

**Comment by zengsn** [comment]
那我把这个关掉
